### ISSUE TITLE
Import examples

### ISSUE THREAD

**Issue by ghost** [mrmikardo/svelte-hcaptcha#2]
Hello, just installed this package. Is it possible to know the correct import instructions? The README file doesn't seem to give any clues :(

**Comment by mrmikardo** [comment]
~~Hey @VentGrey you should be able to import this as a standard ES6 module, i.e. `import HCaptcha from "svelte-hcaptcha";`. Let me know if that doesn't work out and I can provide more details.~~

Edit: need to get this published as a proper package, with `index.js` etc. in order to use as an npm module.

**Comment by mrmikardo** [comment]
@VentGrey I've just published v0.1.1, which fixes the import issue you _may_ have been experiencing.
